### ISSUE TITLE
Add toggle to make auto-creation of playlists on spotify optional?

### ISSUE THREAD

**Issue by justinperkins** [mdoyle13/spotify-weekly#8]
Just an idea. I don't exactly need a playlist for every week. For me I'd like to be able to create a playlist for any past week (since turning on the service) at the click of a button

**Comment by mdoyle13** [comment]
I think this is a good idea. I think turning using the toggle on the edit account page should just be changed to behave that way. There's no point to having an account if the playlists are not being at least backed up into the sites database.

So I think what I'll do is make the "auto_sync" boolean on the user model determine wether the playlist gets created on Spotify or not when the weekly job runs. That sound cool?

**Comment by justinperkins** [comment]
Yup makes perfect sense. I'm not good about staying up to date on my github notifs
